In [2]:
import numpy as np

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
print(a)

[0 1 2 3 4 5]


In [6]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [10]:
a.shape, a2.shape

((6,), (1, 6))

In [11]:
a3 = a[:, np.newaxis]
a3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
a3.shape

(6, 1)

In [14]:
b = np.array([1,2,3,4,5])
b.shape

(5,)

In [20]:
c = np.array([(1,2,3), 
              (4,5,6)])
c.shape

(2, 3)

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
fives = np.full((3,5), 5)
fives

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [32]:
fives.dtype

dtype('int32')

In [29]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
identity_matrix.dtype

dtype('float64')

In [33]:
type(identity_matrix)

numpy.ndarray

In [34]:
identity_matrix.shape

(5, 5)

In [37]:
a

array([0, 1, 2, 3, 4, 5])

In [35]:
len(a)

6

In [36]:
len(identity_matrix)

5

In [38]:
a.ndim

1

In [41]:
identity_matrix.ndim

2

In [42]:
a.size

6

In [43]:
identity_matrix.size

25

In [52]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [53]:
np.arange(4)

array([0, 1, 2, 3])

In [54]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [64]:
empty = np.empty((2,3))
empty

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
empty[0][1]

1.0

In [67]:
np.linspace(1, 20, num=50)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [78]:
np.linspace(1, 10, num=150, dtype=np.float64)

array([ 1.        ,  1.06040268,  1.12080537,  1.18120805,  1.24161074,
        1.30201342,  1.36241611,  1.42281879,  1.48322148,  1.54362416,
        1.60402685,  1.66442953,  1.72483221,  1.7852349 ,  1.84563758,
        1.90604027,  1.96644295,  2.02684564,  2.08724832,  2.14765101,
        2.20805369,  2.26845638,  2.32885906,  2.38926174,  2.44966443,
        2.51006711,  2.5704698 ,  2.63087248,  2.69127517,  2.75167785,
        2.81208054,  2.87248322,  2.93288591,  2.99328859,  3.05369128,
        3.11409396,  3.17449664,  3.23489933,  3.29530201,  3.3557047 ,
        3.41610738,  3.47651007,  3.53691275,  3.59731544,  3.65771812,
        3.71812081,  3.77852349,  3.83892617,  3.89932886,  3.95973154,
        4.02013423,  4.08053691,  4.1409396 ,  4.20134228,  4.26174497,
        4.32214765,  4.38255034,  4.44295302,  4.5033557 ,  4.56375839,
        4.62416107,  4.68456376,  4.74496644,  4.80536913,  4.86577181,
        4.9261745 ,  4.98657718,  5.04697987,  5.10738255,  5.16