In [1]:
!pip install opencv-python

In [2]:
import numpy as np
import cv2 as cv

In [3]:
img = cv.imread('test_01.jpg')

In [4]:
img.shape

(720, 1280, 3)

In [5]:
cv.imshow('image', img)
cv.waitKey(0)
cv.destroyAllWindows()

In [6]:
# convert the image into grayscale and check size
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
gray.shape

(720, 1280)

In [8]:
cv.imshow('image', gray)
cv.waitKey(0)
cv.destroyAllWindows()

In [24]:
# read webcam using CV
cap = cv.VideoCapture(0)

if cap.isOpened():
    ret, frame = cap.read()
    print(ret)
    print(frame)
else:
    ret = False
    
while True:
    ret, frame = cap.read()
    cv.imshow('frame', frame)
    if cv.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv.destroyAllWindows()

True
[[[145 152 166]
  [145 152 166]
  [144 152 165]
  ...
  [127 157 118]
  [108 130 111]
  [ 93 112 103]]

 [[144 153 164]
  [143 152 163]
  [143 152 163]
  ...
  [131 159 123]
  [105 127 108]
  [ 88 107  98]]

 [[142 154 160]
  [142 153 160]
  [141 152 160]
  ...
  [125 151 118]
  [ 90 112  94]
  [ 74  94  84]]

 ...

 [[129 145 127]
  [129 146 127]
  [130 147 127]
  ...
  [104 121 108]
  [103 120 109]
  [102 120 110]]

 [[128 145 125]
  [128 145 125]
  [128 145 124]
  ...
  [106 121 107]
  [104 121 108]
  [103 119 108]]

 [[124 141 120]
  [124 141 120]
  [125 143 120]
  ...
  [105 120 105]
  [105 121 107]
  [103 120 107]]]


In [22]:
cap.release()
